emgapi/models.py, emgapi/serializers.py, emgapi/urls.py, emgapi/views.py, emgapi/views_relations.py, tests/integration/test_biome.py, tests/integration/test_default.py
Add top10 biomes view with the respect of biome tree hierachy
=> top10 biomes view

emgapi/filters.py, emgapi/models.py, emgapi/views.py, tests/integration/test_default.py, tests/integration/test_runs.py
THis PR allow more filter parameters, load all metadata at once and code refactoring
=> Final fixes

emgapianns/management/commands/import_summary.py, emgapianns/serializers.py, emgapianns/views.py, tests/integration/metadata/path/version_1.0/ABC_FASTQ/ABC_FASTQ_summary.ipr, tests/integration/metadata/test_annotations.py
=> Annotations

emgapi/serializers.py, emgapianns/views.py
=> Minor fixes

emgapianns/views.py, tests/integration/test_annotations.py
raise Http404 when object is not found
=> raise Http404 when object is not found

.travis.yml, docker/run.sh, tests/integration/test_examples.py
Test properly all python versions
=> improve tests

database/schema.sql, emgapi/migrations/0002_cleanup_and_rename.py, emgapi/models.py, emgapi/serializers.py
=> clean up migration and schema

emgapi/views.py, emgui/templates/rest_framework/base.html, emgui/templates/rest_framework_swagger/index.html
=> Minor updates

emgapi/filters.py
This PR allows to choose multiple experiment type filters
=> allow multiple experiment types

emgapi/filters.py, emgapi/serializers.py
This PR allows to filter samples and runs by coma separated values in experiment type
=> experiment type filter

emgapi/serializers.py, emgapi/urls.py, emgapi/views_relations.py, tests/integration/test_default.py
This PR adds new endpoint that list analysis results for pipeline version
=> pipeline analysis results relation endpoint

emgapi/filters.py, emgapi/views.py, emgapi/views_relations.py, tests/integration/test_default.py, tests/integration/test_runs.py, tests/integration/test_sample.py
This PR fixes include statement on samples
=> Include on sample

emgapi/filters.py, requirements.txt
THis PR fix issues with django_filters and failing migration due to lack of tables.
=> Fix filter

.travis.yml, README.rst, docker/Dockerfile, docker/config.yaml, docker/docker-compose.yml, docker/run.sh, emgapi/filters.py, emgapianns/views.py, setup.py
This PR fixes study filter on run.
=> fix study filter on runs

MANIFEST.in, emgcli/settings.py
Modifications to enable testing as part of ebi-metagenomics-client CI.
=> Login testing

emgapi/urls.py, emgapi/views.py, emgapianns/views.py, emgcli/settings.py, emgcli/urls.py
Improve error message for `annotations/organisms/<lineage>/analysis`
=> Banner Message endpoint and minor refactor.

.travis.yml, emgapi/filters.py
=> Use the pipeline reselease version to filter

README.rst, setup.py
=> Bump version 1.6.4

emgapianns/serializers.py, tests/integration/test_genomes.py
Fix unit tests for import_genomes.py.
=> Remove unused serializer fields for A.Contigs.

emgapianns/models.py, setup.py
The indexes are breacking the API, some queries are trying to create
the indexes at running time.
=> Contigs model comment indexes (already placed in Mongo).

README.rst, emgapi/admin.py, emgapi/filters.py, emgapi/migrations/0015_genomes.py, emgapi/models.py, emgapi/serializers.py, emgapi/templates/biome_predictor_widget.html, emgapi/urls.py, emgapi/views.py, emgapi/widgets.py, emgcli/dashboard.py, emgcli/settings.py, emgcli/urls.py, gunicorn.sh, requirements-admin.txt, requirements-local-dev.txt, run-tests.sh
Custom dashboard using django-grappelli.
Biom predictor integrated.
Performance improvements for some models (will improve API too)
=> Admin panel for API.

emgapianns/management/commands/import_summary.py
Remove all the annotations and then add the new ones.
Re-import is idempotent now.
=> Import Summary (ko, grpos,...) clean and then import.

emgapi/models.py
An annotate with Count on a many-to-many was making an extra
join that was degrading the performance.
Replaced this with a subquery and the performance is acceptable now.
=> Use a subquery to improve the query performance.

emgapianns/management/lib/study_summary_generator.py
MySQL closes the connections after 28000s, for studies with > 100
analysis this is not enough. To fix this, each time the command
needs to use the db we clear the connections.
=> Study Summary import - MySQL connection issue fix

emgapi/models.py, tests/api/test_permissions.py, tests/webuploader/test_import_checksums.py
Also initial refactor of the auth mechanism.
=> Fix for private/public analysis issue.

.gitignore, config/local.yml, docker/Dockerfile
Improves the local dev setup (especially when using the mgnify-web docker-compose wrapper repo), by enabling Django Admin console and fixing static files serving.
=> Enables Django Admin by default for local development

emgapianns/management/commands/import_genomes.py
This PR:
- Adds a check of whether genome files are present in the filesystem, and whether they are empty files
- Allows **some** files to be empty/missing (if expected/allowable, like some annotations) but raises an error for others (e.g. the sequence file)
This is required because newer MAG catalogues no longer have antiSMASH annotations. In some cases a MAG will have no annotations of a certain type, and we prefer to have no empty files for download on the website.
=> Check for existence/emptiness of genome files on import

.github/workflows/test.yml, README.md, ci/configuration.yaml, emgapianns/management/commands/create_study_summary.py, emgapianns/management/commands/import_analysis.py, emgapianns/management/commands/import_sample.py, emgapianns/management/commands/import_study.py, emgapianns/management/lib/__init__.py, emgapianns/management/lib/create_or_update_study.py, emgapianns/management/lib/europe_pmc_api/europe_pmc_api_handler.py, emgapianns/management/lib/genome_util.py, emgapianns/management/lib/sanity_check.py, emgapianns/management/lib/study_summary_generator.py, emgapianns/management/lib/utils.py, emgcli/settings.py, emgcli/webuploader.py, requirements-webuploader.txt, tests/conftest.py, tests/webuploader/test_annotations.py, tests/webuploader/test_examples.py, tests/webuploader/test_import_study.py, tests/webuploader/test_qc.py, tests/webuploader/test_study_summary_generator.py
Related PR => https://github.com/EBI-Metagenomics/mi-automation/pull/1
=> [Codon] remove emg backlog dependency

docker/Dockerfile, docker/tests.Dockerfile, emgapi/views.py, emgcli/urls.py, emgui/static/nginx_mirror/js/krona-2.0-customized.js
This PR:
- fixes the searching for a file path to `krona.html` for old (v1, v2...?) pipelines, that didn't place the `krona.html` file in a subdir.  In these cases, there is a single file at `...taxonomy-summary/krona.html` with SSU data.
- fixes some dependency installations when running emg api in the mgnify-web docker compose.
- adds a debug serving of the krona plot javascript locally via staticfiles, since this is served via nginx on prod.
=> Fix krona plot on old pipeline versions

emgena/management/commands/sync_assemblies_with_ena.py, tests/ena/test_sync_assemblies_with_ena.py, tests/test_utils/emg_fixtures.py
Extended the sync rules and fixes on ENA db to be used.
=> Fix ENA ~ Assemblies sync.

.github/workflows/test.yml, README.md, docker/lite.Dockerfile, docker/tests.Dockerfile, emgapianns/management/commands/import_assembly.py, emgapianns/management/commands/import_run.py, emgapianns/management/commands/import_sample.py, requirements-webuploader.txt, requirements.txt
The biggest change is related to the samples.
Upgraded the ena-api-handler, I've also included it the base reqs.txt file (pinning the version).
=> Changes to be compliant with ENA's Portal API v2.0

emgapianns/management/commands/import_sample.py, requirements.txt, tests/webuploader/test_import_samples.py
ENA changed status_id to status and int values to public/private
=> Fix status field

config/local-tests.yml, emgapi/management/commands/mgx_api.py, emgapi/metagenomics_exchange.py, emgcli/settings.py, tests/me/test_metagenomics_exchange.py
- Refactored the cli wrapper
- Refactored the settings to be in line with the rest
- Modified the unit tests
=> My revised version:

emgapi/models.py, emgcli/__init__.py, emgena/management/commands/sync_assemblies_with_ena.py, emgena/management/commands/sync_runs_with_ena.py, emgena/management/commands/sync_samples_with_ena.py, emgena/management/commands/sync_studies_with_ena.py, pyproject.toml, tests/ena/test_sync_samples_with_ena.py, tests/ena/test_sync_studies_with_ena.py
Fixes for:
- progress logs
- not returning suppressed data
=> Suppression propagation fixes

emgapianns/management/lib/create_or_update_study.py
Webuploader is failing after our change last week!! Trying both primary and secondary study accession as the filenames are different. We never know which one we're going to get so best to try all.
=> check both primary and secondary accession in ena db
