- emgapi/renderers.py
- emgapi/views.py
- emgcli/pagination.py
Paginate the CSV results for the CSV renderer, and fix for single elements.
Added a simple paginator on the samples endpoint that is faster because
it just returns the pk for the count (useful for complex queries)
> Fix the csv renderer and small perf on samples endpoint.

- emgapianns/models.py
Indexes for contigs are managed separately (due to the size of the
collection).
auto_create_index=False will prevent mongo from checking if the
indexes match the meta of the class. If manually managed then
the names or order the keys maybe slightly different.
> Mongo contigs disable auto index creation.

- emgapianns/management/commands/clean_study.py
A very basic first iteration of a command to remove analysis download files. This was coded to clean ITS/rRNA results from analysis, mostly due to issues with the dev of the v5 pipeline.
> Clean Study download files command

- emgena/models.py
- emgena/serializers.py
- requirements-test.txt
- tests/api/test_csv_rendered.py
- tests/conftest.py
- tests/test_utils/emg_fixtures.py
- tests/webuploader/test_notify.py
RT Tickets API rule:
If this is a consent approval then the procedure is:
- create ticket in ENA-MG queue
- add EMG email in CC (to link the tickets)
otherwise:
- create ticket in EMG queue
Tested in DEV env.
> Consent RT tickets sent to ENA Queue.

- requirements-test.txt
- tests/conftest.py
Changes required to run the API test suite in py3.4 in Jenkins.
> Jenkings + py3.4 tests run support

- emgapi/serializers.py
If `pipelines` were included in the `/assemblies` endpoint (the default behaviour, or by `/assemblies?fields=pipeline`) then the querying was very slow because the related pipelines query set was annotating every object with a `count`. This annotation doesn't seem to actually be serialized by the Assembly serializer or used in the query, so it can seemingly be replaced by the default, non-annotating, Pipeline queryset manager.
> Improves performance of Assemblies endpoint

- emgapi/mixins.py
- emgapi/renderers.py
- tests/api/test_study.py
This PR:
- Fixes the streaming CSV renderer, which was probably broken during Django 3 migration and related updates to DRF and `djangorestframework-csv`.
- Removes most of our custom code for that.
- Maintains CSV as unpaginated.
- Switches to the library-provided data flatteners which seem to give more usable outputs.
- Adds a basic unit test for the CSV on Studies endpoint.
---
No migrations or perms changes.
> Fix CSV renderer.

- emgapi/mixins.py
We return unpaginated responses when a resource list is requested as CSV. This is intended functionality. This is fine for short query sets but long ones hit an nginx timeout.
This fix overrides the response, if the queryset is big, and returns an error with an instruction to use the (paginated) API to access these data.
Response is JSON, unless the client accepts HTML in which case it is the Browsable API (html) page with the error. So users of the API Browser will see a pretty error, users of scripts/curl etc will see some short JSON.
> Prevent timeouts when CSV'ing long querysets

- emgena/models.py
- emgena/serializers.py
- setup.py
- tests/webuploader/test_notify.py
* Notify serializer supporting comma separated emails in from_email
* support for CC when opening a ticket
* CC field in notifications is optional
* notification: only validate field if in initial_data
* Notification: cc is not required
* Update emgena/serializers.py
* strip email when validating notifications
> Multiple emails

- emgapi/models.py
- emgapi/views.py
- emgapi/views_relations.py
- emgapi/viewsets.py
- emgapianns/views.py
- requirements-dev.txt
- requirements-test.txt
- requirements-webuploader.txt
- requirements.txt
This enables the `__search` lookup in CharFields and TextFields, which is then used in the same API fields as in the latest version (8baec5ea6067129d6b98f5757b04bb19281f0352) before the Django 3 update.
At the end it was as simple as adding the suggestion from [here](https://docs.djangoproject.com/en/3.2/releases/1.10/#search-lookup-replacement) in the `models.py`. Which uses `__search` lookup as a `BINARY MODE` full text search in MySQL, as seen [here](https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html).
It also updates a few dependencies.
> Enabling fulltext

- emgapianns/management/commands/import_assembly.py
- emgapianns/management/commands/import_run.py
- emgapianns/management/commands/import_sample.py
- emgapianns/management/lib/create_or_update_study.py
- emgapianns/management/lib/utils.py
- emgena/models.py
This PR:
- (hopefully) resolves issues with missing/unexpected formatting in config files, that have probably existed since https://github.com/EBI-Metagenomics/emgapi/pull/199
- adds a minimal level of compatibility with the ENA database, which runs on Oracle11g. Oracle11g support was dropped by Django after version 1.11. 
- This means the ENA connection has not worked since https://github.com/EBI-Metagenomics/emgapi/pull/204
- Django 1.11LTS end-of-life was last year. Oracle11g end-of-life was December, so is now unsupported.
- We cannot switch entirely to the ENA API because a few fields we need are not there currently, but when they are we should stop querying the ENA databases directly from these webuploader commands.
- the compatibility is based on overriding `.filter()` and `.get()` …
> Webuploader fixes: config files and Django3/Oracle11 incompatibility 

- emgapianns/management/lib/utils.py
Previously Study names/descriptions were being unicode normalised, and then encoded to ASCII. In Python3, this generates a `b''` string, which Django then encodes literally (i.e. `b'the name of study'` is the database value / what is rendered in Views). Since Python 3 has default unicode strings, we shouldn't need this encoding any more.
> Stop ASCII encoding study names/abstracts, since webuploader is now py3

- emgapi/views.py
- emgena/serializers.py
- tests/conftest.py
- tests/webuploader/test_notify.py
**NOTE:** Only merge this PR once the RT Rest API is updated, which is scheduled for the 2nd week of January.
The code changes in this PR are minimal and basically is just formating the requests to the RT API as a Json, and using a token for authentication.
The token can be created by the RT user once the new version is released.
> To get a token Visit "Logged in as ___" -> Settings -> Auth Tokens. Create an Auth Token, give it any description (such as "REST2 with curl"). Make a note of the authentication token it provides to you and treat this token as you would with your password.
Once you have a token, change the config.yaml removing the password and adding a ticket, for example, for testing purposes you can use `testdesk2` with a configuration like 
```yaml
url: …
```
> changes to support the RT rest API 2.0

- emgapi/models.py
- emgapi/viewsets.py
- emgcli/settings.py
- requirements.txt
This commit has a patch for the analyses endpoint. the performance
issue is caused by bug in MySQL (https://code.djangoproject.com/ticket/22438)
I need to test this a bit more before releasing it.
> Patch to workaround performance issues caused by MySQL on the analyses endpoint.

- emgapianns/management/commands/import_contigs.py
- emgapianns/management/commands/import_summary.py
This PR:
- speeds up `import_analysis`, by:
- increase batch size of contigs written to mongo (tiny improvement)
- avoid querying mongo to check existence of each annotation entity (e.g. an InterPro identifier document). Instead, query for all of the entities referenced by an analysis summary and batch create those missing.
- switch from loops to maps when iterating through contig annotations.
Altering the mongodb insertion `write_concern` to `{'w': 0}` (i.e. do not await confirmation of insertion) made no difference, and is a bit risky, so that isn't included.
Combined these give around 20% speedup to `import_analysis`.
> Optimise upload of contigs/annotations into mongodb

- emgena/management/commands/sync_assemblies_with_ena.py
- emgena/management/commands/sync_runs_with_ena.py
- emgena/management/commands/sync_samples_with_ena.py
- emgena/management/commands/sync_studies_with_ena.py
- tests/ena/test_sync_assemblies_with_ena.py
- tests/ena/test_sync_runs_with_ena.py
- tests/ena/test_sync_samples_with_ena.py
- tests/ena/test_sync_studies_with_ena.py
Modifying the QS .using each time we want to use
those models is bad pattern. I didn't change that
as we want to migrate to the ENA in the short term.
> ENA sync commands - set the DB for the QS.

- emgapi/management/commands/download_files_report.py
- emgapi/serializers.py
- emgapi/views_relations.py
This PR:
- expands the `download_files_report` management command to include every type of download. This is a command for sanity checking whether files exist in the filesystem at paths referenced in the DB.
- includes a de-duplication bugfix for the biomes>studies endpoint
> Expanded download files report

- emgapi/models.py
This PR:
- fixes a bug where authenticated users could **only** see their own private `Run`s (and not public ones). Likely a typo.
> Allows authenticated users to see public runs

- emgena/models.py
ERA needs to be appended as the default connection tries to use the PUBLIC SYNONYM (according to ENA) and it's not working ATM we were advised to prefix the views and this is the simplest way. The short-term plan is to remove the dependency of ENA databases
> Workaround to query ENA / ERAPRO Views.

- config/local-lite.yml
- emgena/models.py
This PR:
- fixes the ability for the mgnify-web Taskfile task to automatically create a text DB fixture.
- the inability to do so was a regression bug, introduced by a workaround needed for the ERA tablespace on ENA's Oracle DB, which recently stopped routing Views automatically to the default tablespace. Unforunately, SQlite doesn't support `.` in table names, or tablespaces, so our "fake" ENA database can't perfectly match ERA. This adds a workaround for that.
> Fixes regression bug due to ERA Tablespace workaround

- emgcli/settings.py
It has been observed that the downloading private studies has been failing due to authentication problems. 
Since we updated the APIs to work with JWT based auth, the private study downloads seemed to have been affected by this.
This Pull request addresses this issue by adding an auth cookie, when a JWT token is obtained from the API.
> Setting cookies after jwt auth obtain call is made

- emgapi/management/commands/populate_metagenomics_exchange.py
- emgapi/metagenomics_exchange.py
If ME post request doesn't work - it raised error and fail for whole run. This fix will skip that study raising HTTP error and continue with next study in list
> Add skipping mechanism for list of studies

- emgapi/management/commands/populate_metagenomics_exchange.py
- emgapi/metagenomics_exchange.py
- Add check for missing records in DB (by some reason?)
- Add retries for add_analysis function in case of error 500
> Some tiny fixes for ME scripts

- emgapianns/management/commands/import_extra_run_annotations.py
- emgcli/__init__.py
- pyproject.toml
the import run extra annotations script was initially written to extract accessions from motus_ specific RO crates with SRR values in their accession. 
It's been adjusted to make it work with any accession prefix, e.g ERZ, SANTTIS etc
> Adjusted run annotations import script to be accession agnostic

- emgapianns/management/lib/create_or_update_study.py
Modified searching for project data from Project model to try both RunStudy and AssemblyStudy. This is because Project does not contain a field for secondary accessions containing "RP" and we have edge cases where only secondary accessions exists and no "PRJ" primary accession.
> change to run study and assembly study model for cases where one project accession doesn't work
